name = "numerical_analysis"
license = "BSD 3-Clause"
author = "Jeff Irwin"

#maintainer = "jane.doe@example.com"
#copyright = "Copyright 2021, Jane Doe"

description = "exercises from 'introduction to numerical analysis' by stoer and bulirsch"
categories = [""]
homepage = "https://github.com/JeffIrwin/numerical-analysis"

[build]
auto-executables = true
auto-tests       = true
auto-examples    = true
#module-naming    = true
module-naming    = "numa"
# Maybe I should rename the project for consistency.  "numerical_analysis" is
# too long to be typing

[install]
library = true

#[[executable]]
#name = "numerical_analysis"
#source-dir = "src"
#main = "main.f90"

[[test]]
# TODO: refactor src dir to move test.f90 and related files into a sibling test
# dir (like default fpm template layout, see fynth)
name = "test"
source-dir = "src"
main = "test.f90"

