
!> \mainpage Numerical analysis main page
!>
!> Most of the functions for numerical analysis are in the \ref numa module.
!>
!> The source code is hosted on github:
!>
!> https://github.com/JeffIrwin/numerical-analysis
!>
!> This documentation is automatically generated by Doxygen.
!>

!===============================================================================

#include "panic.F90"

!> Main public-facing module for numerical analysis
module numa

	use numa__blarg
	use numa__core
	use numa__eig
	use numa__fit
	use numa__integrate
	use numa__interp
	use numa__linalg
	use numa__linprog
	use numa__opt
	use numa__utils

	implicit none

	! TODO:
	!
	! - this file is too long. it might be good to split it up roughly
	!   per-chapter, e.g. into interpolate.f90, (fft.f90,) integrate.f90, etc.
	!   * wip
	!   * linalg is started. lots of other stuff should move there too
	!   * exercises need split up too
	! - Add ci/cd testing with ifx.  There are a couple workarounds in here
	!   specifically for Intel, e.g. initialization of complex arrays
	! - Add more doxygen doc strings, maybe at least just a `brief` for each
	!   public fn.  See `lagrange_interpolator()` which has an example doc
	!   string

contains

!===============================================================================

end module numa

