
name: CI

on: [push]

jobs:

  test-os:

    name: Test ${{ matrix.os }} ${{ matrix.toolchain.compiler }} ${{ matrix.toolchain.version }}
    runs-on: ${{ matrix.os }}
    strategy:

      # Having multiple matrices (e.g. os *and* gfortran) will test every
      # possible combination of those two matrices!
      matrix:
        #os: [ubuntu-latest]
        #os: [ubuntu-latest, macOS-latest]
        os: [ubuntu-latest, windows-latest]
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        toolchain:
          - {compiler: gcc, version: 12}
          - {compiler: gcc, version: 13}
          - {compiler: intel, version: 2024.2}
          #- {compiler: lfortran, version: '0.51.0'}
        exclude:
          - os: windows-latest
            toolchain: {compiler: intel, version: 2024.2}

    steps:

    - uses: actions/checkout@v3
    #- uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}


    - if: matrix.os == 'ubuntu-latest'
      name: Test numerical-analysis on ubuntu-latest
      #env:
      #  FPM_FC: "ifx"
      run: |
        curl -L -o ./fpm https://github.com/fortran-lang/fpm/releases/download/current/fpm-linux-x86_64-gcc-12
        chmod +x fpm
        mv fpm /usr/local/bin
        fpm --version
        gfortran --version
        ./test.sh
        #source /opt/intel/oneapi/setvars.sh

    - uses: actions/checkout@v3
    - uses: fortran-lang/setup-fpm@v7
    - uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}

    - if: matrix.toolchain.compiler != 'intel'
      name: Test numa on ${{ matrix.os }}
      run: |
        fpm run --example --profile debug
        fpm run --example --profile release
        fpm test --profile debug
        fpm test --profile release

    - if: matrix.toolchain.compiler == 'intel'
      name: Test numa on ${{ matrix.os }}
      uses: rscohn2/setup-oneapi@v0
      with:
        list: true
        components: |
          ifx@2024.2.0
          mkl@2024.2.0
      run: |
        fpm run --example --profile debug --flag "-qmkl -standard-semantics"
        fpm run --example --profile release --flag "-qmkl -standard-semantics"
        fpm test --profile debug --flag "-qmkl -standard-semantics"
        fpm test --profile release --flag "-qmkl -standard-semantics"

  test-docker:

    name: Test in docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test in docker
      run: |
        docker build . -t rocky

